### PR TITLE
Fix transcription for longer audio

### LINKED ISSUE #740: Incorrect results from transcribing audio from file
### Description

When developing timestamping in STT I spotted that the results of the STT transcription are a bit off. The first 35 seconds of 58-second audio are recognised as music and audience chattering. Then, transcription is perfectly fine. The audio's quality is the same during the whole listening. The result is presented on the following screenshot:

Image

Reference audio: https://ai.swmansion.com/storage/moonshine/test_audio.mp3

### Steps to reproduce

Run STT example from demo app and pass link from the description.

### Snack or a link to a repository

_No response_

### React Native Executorch version

Main

### React Native version

0.81.5

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 16 Pro

### AI model

model from STT demo app

### Performance logs

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by msluszniak**
## Description

This PR introduces changes that fix transcription for audio longer than 30 seconds. It also fixes Speech to Text demo app. Previously, local paths to audio files hasn't worked. Now they worked.

### Introduces a breaking change?

- [ ] Yes
- [x] No

### Type of change

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Documentation update (improves or adds clarity to existing documentation)
- [x] Other (chores, tests, code style improvements etc.)

### Tested on

- [x] iOS
- [ ] Android

### Testing instructions

Before applying changes:
Run `Speech to text` demo app with audio longer than 30 seconds. Then, check that it has incorrect transcription
Additionally, try to pass path to local audio file and check, that transcription never starts.

Then, apply changes and check if these two issues are resolved

### Related issues

Closes #740 

### Checklist

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly
- [x] My changes generate no new warnings

### CODE REVIEW

File: apps/speech/screens/SpeechToTextScreen.tsx [hunk 1]
```diff
@@ -50,16 +50,30 @@ export const SpeechToTextScreen = ({ onBack }: { onBack: () => void }) => {
...
+      // Case A: Remote URL -> Download it
+      const { uri } = await FileSystem.downloadAsync(sourceUri, destination);
+      return uri;
+    } else {
+      // Case B: Local URI -> Copy it
+      await FileSystem.copyAsync({
+        from: sourceUri,
+        to: destination,
+      });
+      return destination;
```
Comment (msluszniak) [inline apps/speech/screens/SpeechToTextScreen.tsx:64]:
```suggestion
    if (sourceUri.startsWith('http')) {
      const { uri } = await FileSystem.downloadAsync(sourceUri, destination);
      return uri;
    } else {
      await FileSystem.copyAsync({
        from: sourceUri,
        to: destination,
      });
      return destination;
```
