### PR TITLE
chore: Add model selections and small fixes

### LINKED ISSUE #958: Make it easy to switch models in demo apps
Right now, models used in demo apps are fixed and you need to manually change them in app code. It would be great, if you were able to switch between models inside the demo app.

### PR DESCRIPTION
**Pull request by msluszniak**
### Introduces a breaking change?

- [ ] Yes
- [x] No

### Type of change

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Documentation update (improves or adds clarity to existing documentation)
- [x] Other (chores, tests, code style improvements etc.)

### Tested on

- [x] iOS
- [ ] Android

### Testing instructions

Run models from demo apps and check if you can select different models and they works:
- [x] Computer Vision
- [x] LLM
- [x] Speech

Additionally:
- [x] Check that without registering streamInsert demo app with text to speech fails
- [x] Check that without changes in OCR and Vertical OCR demo app fails
- [x] Check that text to image example looks now simpler and better
- [x] Check that image embeddings example works

### Related issues

Closes #958 

### Checklist

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly (Not applicable)
- [x] My changes generate no new warnings

### Additional notes

~Additionally, I found out that links for VLMs are incorrect since they point out to `main` on hugging face. @NorbertKlockiewicz could you create 0.8.0 tag on huggingface as for lfm instruct and change links here: https://github.com/software-mansion/react-native-executorch/blob/main/packages/react-native-executorch/src/constants/modelUrls.ts#L408-L411?~
Thanks

### CODE REVIEW

File: apps/llm/app/llm/index.tsx [hunk 1]
```diff
@@ -11,14 +11,31 @@ import {
...
 import Spinner from '../../components/Spinner';
 
+type LLMModelSources = LLMProps['model'];
+
+const MODELS: ModelOption<LLMModelSources>[] = [
+  { label: 'Llama 1B', value: LLAMA3_2_1B_SPINQUANT },
+  { label: 'Llama 3B', value: LLAMA3_2_3B_SPINQUANT },
+  { label: 'Qwen3 0.6B', value: QWEN3_0_6B_QUANTIZED },
+  { label: 'Qwen3 1.7B', value: QWEN3_1_7B_QUANTIZED },
+];
```
Comment (barhanc) [inline apps/llm/app/llm/index.tsx]: Any reason why we don't provide here (and in other LLM apps) all the LLM models?

File: apps/speech/screens/TextToSpeechScreen.tsx [hunk 2]
```diff
@@ -157,6 +188,17 @@ export const TextToSpeechScreen = ({ onBack }: { onBack: () => void }) => {
...
+          <ModelPicker
+            models={TTS_MODELS}
+            selectedModel={selectedModel}
+            onSelect={(m) => setSelectedModel(m)}
+          />
+          <ModelPicker
+            models={VOICES}
+            selectedModel={selectedVoice}
+            onSelect={(m) => setSelectedVoice(m)}
+          />
```
Comment (barhanc) [inline apps/speech/screens/TextToSpeechScreen.tsx:206]:
```suggestion
          <ModelPicker
            label="Model"
            models={TTS_MODELS}
            selectedModel={selectedModel}
            onSelect={(m) => setSelectedModel(m)}
          />
          <ModelPicker
            label="Voice"
            models={VOICES}
            selectedModel={selectedVoice}
            onSelect={(m) => setSelectedVoice(m)}
          />
```

File: apps/computer-vision/app/text_to_image/index.tsx
Comment (barhanc) [inline apps/computer-vision/app/text_to_image/index.tsx:1]: Trying to switch the model while generating crashes the app.

File: apps/llm/app/llm/index.tsx (hunk 1 above)
Comment (msluszniak) [reply apps/llm/app/llm/index.tsx]: Yeap, we should probably provide all LLMs here.

File: apps/speech/screens/TextToSpeechScreen.tsx [hunk 3]
```diff
@@ -10,10 +10,35 @@ import {
...
+
+const VOICES: ModelOption<VoiceConfig>[] = [
+  { label: 'AF Heart', value: KOKORO_VOICE_AF_HEART },
+  { label: 'AF River', value: KOKORO_VOICE_AF_RIVER },
+  { label: 'AF Sarah', value: KOKORO_VOICE_AF_SARAH },
+  { label: 'AM Adam', value: KOKORO_VOICE_AM_ADAM },
+  { label: 'AM Michael', value: KOKORO_VOICE_AM_MICHAEL },
+  { label: 'BF Emma', value: KOKORO_VOICE_BF_EMMA },
+  { label: 'BM Daniel', value: KOKORO_VOICE_BM_DANIEL },
+];
```
Comment (IgorSwat) [inline apps/speech/screens/TextToSpeechScreen.tsx:43]:
```suggestion
const VOICES: ModelOption<VoiceConfig>[] = [
  { label: 'AF Heart', value: KOKORO_VOICE_AF_HEART },
  { label: 'AF River', value: KOKORO_VOICE_AF_RIVER },
  { label: 'AF Sarah', value: KOKORO_VOICE_AF_SARAH },
  { label: 'AM Adam', value: KOKORO_VOICE_AM_ADAM },
  { label: 'AM Michael', value: KOKORO_VOICE_AM_MICHAEL },
  { label: 'AM Santa', value: KOKORO_VOICE_AM_SANTA },
  { label: 'BF Emma', value: KOKORO_VOICE_BF_EMMA },
  { label: 'BM Daniel', value: KOKORO_VOICE_BM_DANIEL },
];
```

File: apps/computer-vision/app/text_to_image/index.tsx
Comment (msluszniak) [reply apps/computer-vision/app/text_to_image/index.tsx:1]: I blocked this option explicitly in apps.

File: apps/llm/app/llm/index.tsx (hunk 1 above)
Comment (msluszniak) [reply apps/llm/app/llm/index.tsx]: Added all llms.

File: apps/speech/screens/TextToSpeechScreen.tsx [hunk 4]
```diff
@@ -10,10 +10,36 @@ import {
 } from 'react-native';
 import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
 import {
+  KOKORO_SMALL,
   KOKORO_MEDIUM,
   KOKORO_VOICE_AF_HEART,
+  KOKORO_VOICE_AF_RIVER,
+  KOKORO_VOICE_AF_SARAH,
+  KOKORO_VOICE_AM_ADAM,
+  KOKORO_VOICE_AM_MICHAEL,
```
Comment (msluszniak) [inline apps/speech/screens/TextToSpeechScreen.tsx:19]:
```suggestion
  KOKORO_VOICE_AM_MICHAEL,
  KOKORO_VOICE_AM_SANTA,
```

**Comment by msluszniak** [comment]
@barhanc @IgorSwat I addressed your suggestions, also fixed image embeddings demo app, please check this during re-review.
