### PR TITLE
chore: Fix bounding box annotation

### LINKED ISSUE #975: Make bounding boxes coherent across demo apps
https://github.com/software-mansion/react-native-executorch/pull/893#issuecomment-4076242516

### PR DESCRIPTION
**Pull request by msluszniak**
## Description

This PR fixes the problem in demo apps where bounding boxes were utilized. For small objects annotation width was set to width of the bounding box since they were in the same view. Fix is to make these two be in relation child - parent components.

### Introduces a breaking change?

- [ ] Yes
- [x] No

### Type of change

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Documentation update (improves or adds clarity to existing documentation)
- [x] Other (chores, tests, code style improvements etc.)

### Tested on

- [ ] iOS
- [x] Android

### Testing instructions

- [ ] Compare result of annotation for apps that utilizes bounding boxes for small detected objects. 

### Screenshots

Now bounding boxes on small objects looks correct (in the #975 was the original result for the same image):
image

### Related issues

Closes #975

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by msluszniak** [comment]
~TODO: Unify this with with bounding boxes from vision camera so all bounding boxes will be in different colors plus apply these changes to examples from vision camera.~
DONE

File: apps/computer-vision/components/vision_camera/utils/colors.ts [hunk 1]
```diff
@@ -1,41 +1 @@
...
-export function labelColor(label: string): string {
-  const color = CLASS_COLORS[hashLabel(label)]!;
-  return `rgba(${color[0]},${color[1]},${color[2]},1)`;
-}
-
-export function labelColorBg(label: string): string {
-  const color = CLASS_COLORS[hashLabel(label)]!;
-  return `rgba(${color[0]},${color[1]},${color[2]},0.75)`;
-}
+export * from '../../utils/colors';
```
Comment (NorbertKlockiewicz) [inline apps/computer-vision/components/vision_camera/utils/colors.ts]: I think we can completely skip this file and import directly from the utils/colors.ts

File: apps/computer-vision/components/BoundingBoxes.tsx [hunk 2]
```diff
@@ -0,0 +1,85 @@
+import React from 'react';
+import { StyleSheet, Text, View } from 'react-native';
+import { Detection } from 'react-native-executorch';
+import { labelColor, labelColorBg } from './utils/colors';
+
+interface Props {
+  detections: Detection[];
+  scaleX: number;
```
Comment (chmjkb) [inline apps/computer-vision/components/BoundingBoxes.tsx]: It's no biggie but since Detection is generic maybe we can make this generic as well and pass labels from the demo apps

**Comment by msluszniak** [comment]
> Can we do something about the case where an object is at the edge of a picture, and the label text is clipped? Image

I'll add ellipsis to make it looking like this:
image
